### ISSUE TITLE
references.groovy file when running test

### ISSUE THREAD

**Issue by tijeco** [Oshlack/MINTIE#19]
I've recently tried installing and running mintie on the test dataset and have run into a few issues.

I've installed mamba using the following:
```
mamba create -c conda-forge -c bioconda -n mintie mintie
```

This gives me mintie=0.3.9-0

I then run the parameter to setup the test data:

```
mintie -t
```

Which made the following files:
```
├── cases
│   ├── allvars-case_R1.fastq.gz
│   └── allvars-case_R2.fastq.gz
├── controls
│   ├── allvars-control_R1.fastq.gz
│   └── allvars-control_R2.fastq.gz
└── test_params.txt

2 directories, 5 files
```

Then, I ran the following mintie commands:

```
mintie -w -p test_params.txt cases/*.fastq.gz controls/*.fastq.gz
```

I get the following output:

```
=========================================== Bpipe Error ============================================

An error occurred executing your pipeline:

A script, requested to be loaded from file '/home/jcole/miniconda3/envs/mintie/share/mintie-0.3.9-0/references.groovy', could not be accessed.


Please see the details below for more information.

========================================== Error Details ===========================================

bpipe.PipelineError: A script, requested to be loaded from file '/home/jcole/miniconda3/envs/mintie/share/mintie-0.3.9-0/references.groovy', could not be accessed.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at MINTIE.groovy.run(MINTIE.groovy:15)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


====================================================================================================

More details about why this error occurred may be available in the full log file .bpipe/bpipe.log
```

Indeed, references.groovy does not exist. Is there something I need to do to generate that file?

**Comment by mcmero** [comment]
This indicates that the references MINTIE requires haven't been set up. Try running:

```
mintie -r
```

**Comment by tijeco** [comment]
@mcmero Thanks! I had a feeling I was missing something very simple.
