### ISSUE TITLE
Key error: 'chrchr19'

### ISSUE THREAD

**Issue by RoopanGiri** [Oshlack/MINTIE#38]
Hello,

I'm currently trying to run a simulation through MINTIE using the run_simu.py files in the simu folder. I have resolved most of the issues I have encountered except the following.

```
python run_simu.py params.ini --log simulog.txt
Traceback (most recent call last):
  File "/home/neuro/miniconda3/envs/mintie/run_simu.py", line 345, in <module>
    main()
  File "/home/neuro/miniconda3/envs/mintie/run_simu.py", line 342, in main
    simulate(args)
  File "/home/neuro/miniconda3/envs/mintie/run_simu.py", line 321, in simulate
    available_genes = simulate_fusions(simp, params, available_genes, valid_txs,
  File "/home/neuro/miniconda3/envs/mintie/run_simu.py", line 124, in simulate_fusions
    fus_parts = simu.write_fusion((tx1, tx2), (gene1, gene2), all_exons, paths['genome_fasta'], \
  File "/home/neuro/miniconda3/envs/mintie/simu.py", line 595, in write_fusion
    block_seq = get_random_block(chr1, gene_trees, genome_fasta, block_range)
  File "/home/neuro/miniconda3/envs/mintie/simu.py", line 397, in get_random_block
    chr_range = chr_sizes[('chr%s' % chrom)]
KeyError: 'chrchr19'
```

I'm not entirely sure how to proceed.

Thanks for the help!

**Comment by mcmero** [comment]
The simu script assumes that you use the chromosome naming format 1, 2, ... X, Y etc. rather than chr1, chr2 etc. Try changing your GTF file to use this chromosome name convention.

**Comment by RoopanGiri** [comment]
Thanks!

Would changing the code in simu.py to `chr_range = chr_sizes[('%s' % chrom)]` have the same effect or would this disrupt other parts of the code?

**Comment by mcmero** [comment]
It should have the same effect, as long as all your other reference files are consistent in chromosome naming. It's been a few years since I wrote the script, so I can't say for certain that it won't affect other parts of the code.
