### ISSUE TITLE
refine_annotations.py: 'DataFrame' object has no attribute 'valid_motif'

### ISSUE THREAD

**Issue by wdecoster** [Oshlack/MINTIE#7]
Hi,

After successfully using MINTIE for some samples running the pipeline for one raised the following error, replacing a confidential sample identifier with "<sample>":
If necessary I can share a file (through email). Could you let me know which file would be most informative for you? Or is there something else you want me to do to debug?

Greetz,
Wouter

```
================================== Command refine_contigs (1999) ===================================

Command    : python /home/wdecoster/mintie/MINTIE/annotate/refine_annotations.py             <sample>/annotated_contigs_info.tsv <sample>/annotated_contigs.vcf <sample>/annotated_contigs.bam /home/wdecoster/mintie/MINTIE/ref/chess2.2.gtf             /home/wdecoster/mintie/MINTIE/ref/hg38.fa <sample>/novel_contigs             --minClip 20             --minGap 7             --mismatches 0             --log /home/wdecoster/mintie/<sample>/refine.log > <sample>/novel_contigs.vcf ; samtools index <sample>/novel_contigs.bam ; python /home/wdecoster/mintie/MINTIE/util/filter_fasta.py <sample>/de_contigs.fasta <sample>/novel_contigs_info.tsv --col_id contig_id > <sample>/novel_contigs.fasta ;
Started    : Mon Sep 21 13:23:24 CEST 2020
Stopped    : Mon Sep 21 13:23:33 CEST 2020
Exit Code  : 1
Config: 
                   Name           |  Value  
          ----------------------------------
          max_per_command_threads | 16      
          executor                | local   
          concurrency             | 32      
          walltime                | 20:00:00
          queue                   | batch   
          mem_param               | mem     
          memory                  | 8       
          proc_mode               | 1       
          usePollerFileWatcher    | true    
          manualPollerSleepTime   | 30000   
          maxFileNameLength       | 2048    
          name                    | python  
          procs                   | 1       

Output    : 

        Traceback (most recent call last):
          File "/home/wdecoster/mintie/MINTIE/annotate/refine_annotations.py", line 572, in <module>
            main()
          File "/home/wdecoster/mintie/MINTIE/annotate/refine_annotations.py", line 564, in main
            keep_contigs = get_contigs_to_keep(args)
          File "/home/wdecoster/mintie/MINTIE/annotate/refine_annotations.py", line 510, in get_contigs_to_keep
            is_novel_exon = np.logical_and(is_novel_exon, contigs.valid_motif)
          File "/home/wdecoster/miniconda3/envs/mintie/lib/python3.8/site-packages/pandas/core/generic.py", line 5136, in __getattr__
            return object.__getattribute__(self, name)
        AttributeError: 'DataFrame' object has no attribute 'valid_motif'
```

**Comment by mcmero** [comment]
Hi Wouter,

Thanks for the raising the error. My guess is that you're running into an edge-case while running motif checking. I've just pushed a commit (0e7915e) that should hopefully solve the issue. Let me know if the problem persists.

Cheers,
Marek

**Comment by wdecoster** [comment]
Hi Marek,

Thanks for the quick fix, now it also works for that sample!

Cheers,
Wouter
